# Generated by Django 3.2.4 on 2021-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHM', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='login', max_length=70, verbose_name='cookie'),
        ),
        migrations.AddField(
            model_name='user',
            name='isLogin',
            field=models.BooleanField(default=False, verbose_name='is_login'),
        ),
    ]
