# Generated by Django 3.2.4 on 2021-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHM', '0003_auto_20210716_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='phm', max_length=70, verbose_name='cookie'),
        ),
    ]
