# Generated by Django 3.2.4 on 2021-07-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHM', '0004_alter_user_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='phm', max_length=70, verbose_name='token'),
        ),
    ]
