# Generated by Django 3.2.4 on 2021-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHM', '0006_auto_20210716_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=20, null=True, verbose_name='qq'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(max_length=20, null=True, verbose_name='wechat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(max_length=500, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
