# Generated by Django 3.2.4 on 2021-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHM', '0007_auto_20210716_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, null=True, verbose_name='昵称'),
        ),
    ]
